version: 0.1

#environment_variables:
#  plaintext:
#    TEST: "value1"
#    TEST: "value2"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y golang git
#  pre_build:
#    commands:
#      -
  build:
    commands:
      - export GOPATH=$CODEBUILD_SRC_DIR; go build -o vomit
  post_build:
    commands:
      - mkdir -p vomit-build/$CODEBUILD_BUILD_ID/
      - mv vomit vomit-build/$CODEBUILD_BUILD_ID/
artifacts:
  files:
    - **/*
  discard-paths: no
  base-directory: vomit-build/
